apiVersion: v1
kind: Namespace
metadata:
  name: eks-demo-app

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: access-s3-sa
  namespace: eks-demo-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::919942204431:role/demo-oidc-eks-s3-role